import Head from "next/head";
import Navbar from "../components/Navbar";
import ProductCard from "../components/ProductCard";
import womensShoesImage from "../assets/womens_shoes.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Golden Shoe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>Home Page</div>
      <ProductCard
        title="Womens Shoes"
        text="Fantastic current trends"
        image={womensShoesImage}
      />
    </div>
  );
}
